### ISSUE TITLE
No way to escape from while loop

### ISSUE THREAD

**Issue by LoliPain** [ZemlyakovDmitry/animego_notifier#13]
Using `while True:` with no reason at 
https://github.com/ZemlyakovDmitry/animego_notifier/blob/ef78a1993ac18f79f003a9bf40bd59ec3b1c0fed/bot.py#L82

should be replaced `loop.call_later()` with delay calculation 

Refactor aims to improve perfomance and make code more situational in case if you want to disable notifying

**Comment by ZemlyakovDmitry** [comment]
I'll make a function that will change the state of the notify on command from true to false. Is it a good idea?
