### ISSUE TITLE
Prefer error_dispatcher for api error handling

### ISSUE THREAD

**Issue by LoliPain** [ZemlyakovDmitry/animego_notifier#17]
Some handlers like https://github.com/ZemlyakovDmitry/animego_notifier/blob/ef78a1993ac18f79f003a9bf40bd59ec3b1c0fed/bot.py#L136
are supposed to be excepted only with vk api errors, so it more preferably to use `.error_dispatcher.add_handler` instead try/except clause

**Comment by ZemlyakovDmitry** [comment]
Kill me pls

🙏🙏🙏

**Comment by ZemlyakovDmitry** [comment]
It's more like ping command. So it won't fix.
